kind: 'CDN'
version: '1'
data:
  originSelectors:
    rules:
      - name: route-geo-to-edge-function
        when: { reqProperty: path, equals: "/api/geo" }
        action:
          type: selectAemOrigin
          originName: edgefunction-southwest-geo
          skipCache: true
